### ISSUE TITLE
Startup fails to inject FxWeldApplication during load

### ISSUE THREAD

**Issue by Tzrlk** [cgiesche/javafx-cdi-bootstrap#1]
When running `FxWeldApplication.main` and `FxWeldApplicationLoader.init()` gets subsequently called, the call to `fxWeldApplications.get()` throws the following stacktrace:

```
Exception in thread "main" java.lang.RuntimeException: Exception in Application init method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:912)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.weld.exceptions.UnsatisfiedResolutionException: WELD-001334: Unsatisfied dependencies for type FxWeldApplication with qualifiers  
	at org.jboss.weld.bean.builtin.InstanceImpl.checkBeanResolved(InstanceImpl.java:241)
	at org.jboss.weld.bean.builtin.InstanceImpl.get(InstanceImpl.java:113)
	at de.perdoctus.fx.FxWeldApplicationLoader.init(FxWeldApplicationLoader.java:49)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:841)
	... 2 more
```

Debugging the process told me that `weldContainer.instance().select(FxWeldApplication.class);` wasn't finding any of the needed beans.

I thought my issue might have been the placement of my `beans.xml`, but all the guides were saying that `src/main/resources/META-INF/beans.xml` was the correct place. I'm not sure where to even look next.

The bootstrapping logs tell me that `FxWeldApplication` isn't even attempted to load, though the `FxWeldApplicationLoader` is.

```
2018-01-03 19:09:43 DEBUG Bootstrap:433 - WELD-000106: Bean: Managed Bean [class de.perdoctus.fx.FxWeldApplicationLoader] with qualifiers [@Any @Default]
```

**Comment by cgiesche** [comment]
Hi Tzrlk,

one of my other projects uses this library. Relevant files are:

https://github.com/cgiesche/ebikeconnect-gui/blob/master/src/main/java/de/perdoctus/ebikeconnect/gui/Main.java
(This is the class that extends FxWeldApplication and inherits it's main() method)

https://github.com/cgiesche/ebikeconnect-gui/tree/master/src/main/resources/META-INF
(the interceptor in beans.xml is of course not needed)

As the basic setup is very simple, i can not imagine, what is wrong. I will set up a minimal example app and attach it to this issue.

**Comment by cgiesche** [comment]
This is a minimal size, maximum ugly coded example, but at least it works as expected (run MyApplication):
[cdibootstraptest.zip](https://github.com/cgiesche/javafx-cdi-bootstrap/files/1600521/cdibootstraptest.zip)

**Comment by Tzrlk** [comment]
After looking at your constructor, I saw that the injection annotation was defined on the constructor itself, rather than the individual parameters (which makes perfect sense now I think about it). Once I moved the annotation(s), it picked up the class just fine. Cheers.
